"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { motion, AnimatePresence } from "framer-motion";
import { toast } from "sonner";
import { api } from "@/lib/api";
import { SparkleIcon } from "@/components/ui/icons";

interface AskFormixAICapsuleProps {
  className?: string;
  onSuccess?: () => void;
}

export function AskFormixAICapsule({ className = "", onSuccess }: AskFormixAICapsuleProps) {
  const router = useRouter();
  const qc = useQueryClient();
  const [prompt, setPrompt] = useState("");
  const [isFocused, setIsFocused] = useState(false);

  const generateMutation = useMutation({
    mutationFn: (p: string) => api.generateFormWithAI(p),
    onSuccess: (newForm) => {
      toast.success("✨ Form generated by Formix AI!");
      qc.invalidateQueries({ queryKey: ["forms"] });
      setPrompt("");
      if (onSuccess) onSuccess();
      router.push(`/forms/${newForm.id}/edit`);
    },
    onError: (err: Error) => {
      toast.error(err.message || "Couldn't generate form with AI. Please try again.");
    },
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const p = prompt.trim();
    if (!p) {
      toast.info("Please enter a prompt (e.g. 'Customer feedback survey with 4 questions')");
      return;
    }
    generateMutation.mutate(p);
  };

  const handleVoiceClick = () => {
    toast.info("🎙️ Voice input is coming in the next release!", {
      description: "Type your prompt in the box to generate forms instantly.",
    });
  };

  return (
    <div className={`relative group ${className}`}>
      {/* Subtle glowing ambient background */}
      <div className="absolute inset-0 bg-gradient-to-r from-[#e7dff1] to-[#f0dee7] rounded-xl blur-sm opacity-40 group-hover:opacity-75 transition-opacity" />

      <form
        onSubmit={handleSubmit}
        className={`relative bg-card border ${
          isFocused ? "border-[#261c23] shadow-md ring-2 ring-[#261c23]/10" : "border-border"
        } rounded-xl flex items-center px-3 py-2 gap-2 transition-all duration-200`}
      >
        {/* Mic Icon */}
        <button
          type="button"
          onClick={handleVoiceClick}
          className="text-ink-soft hover:text-ink transition-colors p-0.5 rounded focus:outline-none"
          title="Voice input (Coming soon)"
          aria-label="Voice input"
        >
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <path d="M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3Z" />
            <path d="M19 10v2a7 7 0 0 1-14 0v-2" />
            <line x1="12" x2="12" y1="19" y2="22" />
          </svg>
        </button>

        {/* Input */}
        <input
          type="text"
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          onFocus={() => setIsFocused(true)}
          onBlur={() => setIsFocused(false)}
          placeholder={generateMutation.isPending ? "Generating form..." : "Ask Formix AI"}
          disabled={generateMutation.isPending}
          className="w-full bg-transparent border-none p-0 text-sm text-ink outline-none placeholder:text-ink-soft focus:ring-0"
        />

        {/* Submit Arrow / Loading Spinner */}
        <button
          type="submit"
          disabled={generateMutation.isPending || !prompt.trim()}
          className={`p-1.5 rounded-lg transition-all duration-200 flex items-center justify-center shrink-0 ${
            prompt.trim() && !generateMutation.isPending
              ? "bg-[#261c23] text-white hover:opacity-90 cursor-pointer shadow-sm scale-100"
              : "text-ink-soft opacity-50 cursor-not-allowed"
          }`}
          aria-label="Generate with AI"
        >
          {generateMutation.isPending ? (
            <svg className="animate-spin w-4 h-4 text-ink" viewBox="0 0 24 24" fill="none">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8H4z" />
            </svg>
          ) : (
            <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
              <path d="m22 2-7 20-4-9-9-4Z" />
              <path d="M22 2 11 13" />
            </svg>
          )}
        </button>
      </form>
    </div>
  );
}
